# Generated by Django 5.1.6 on 2025-03-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Not Paid', 'Not Paid'), ('Ready To Ship', 'Ready To Ship'), ('Canceled', 'Canceled'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Not Paid', max_length=20),
        ),
    ]
