# Generated by Django 5.1.6 on 2025-04-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_date_review_created_at_review_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
